#%RAML 1.0 DataType
type: object
displayName: JourneyStep (next)
properties:
    id: integer
    journey :
        type: object
        default : {}
    next_step :
        type: object
        default : {}
    planet_start:
        type : object
        default : {}
    map_pos_x_start: integer
    map_pos_y_start: integer
    planet_final:
        type: object
        default : {}
    map_pos_x_final: integer
    map_pos_y_final: integer
    time_start: datetime
    time_jump: datetime
    time_arrival: datetime
    step_number: integer
