---
version: '3.5'
networks:
    game:
        name: kalaxia_game
        driver: bridge

services:
    front:
        container_name: kalaxia_front
        image: kalaxia/front
        env_file:
            - kalaxia.env
        networks:
            - game

    api:
        container_name: kalaxia_api
        build: .
        image: kalaxia/api
        env_file:
            - kalaxia.env
        networks:
            - game
        volumes:
            - "./rsa_vault:/go/src/kalaxia-game-api/rsa_vault"

    nginx:
        container_name: kalaxia_nginx
        build: build/docker/nginx
        image: kalaxia/nginx
        networks:
            - game
        depends_on:
            - front
            - api
        env_file:
            - kalaxia.env
        volumes:
            # nginx
            - "./volumes/ssl:/etc/ssl"
            - "./volumes/logs/nginx:/var/log/nginx"
        ports:
            - "${NGINX_HTTPS_PORT}:443"
            - "${NGINX_PORT}:80"

    postgresql:
        container_name: kalaxia_postgresql
        image: postgres:9.6
        env_file:
            - kalaxia.env
        networks:
            - game
        volumes:
            - "./volumes/data:/var/lib/postgresql/data"
        ports:
            - "5432"
