---
version: '3.5'
networks:
    game:
        name: ${NETWORK_USER}_game
        driver: bridge

services:
    front:
        container_name: ${NETWORK_USER}_front
        image: kalaxia/front
        env_file:
            - kalaxia.env
        networks:
            - game
        volumes:
            - "./volumes/app:/srv/app"

    api:
        container_name: ${NETWORK_USER}_api
        build: .
        image: ${API_DOCKER_IMAGE}
        env_file:
            - kalaxia.env
        networks:
            - game
        volumes:
            - "./rsa_vault:/go/src/kalaxia-game-api/rsa_vault"

    nginx:
        container_name: ${NETWORK_USER}_nginx
        build: build/docker/nginx
        networks:
            - game
        depends_on:
            - front
            - api
        env_file:
            - kalaxia.env
        volumes:
            # nginx
            - "./volumes/ssl:/etc/ssl"
            - "./volumes/logs/nginx:/var/log/nginx"
        ports:
            - "${NGINX_HTTPS_PORT}:443"
            - "${NGINX_PORT}:80"

    postgresql:
        container_name: ${NETWORK_USER}_postgresql
        image: postgres:9.6
        env_file:
            - kalaxia.env
        networks:
            - game
        ports:
            - "5432"
