#%RAML 1.0
title: Kalaxia Game API
baseUri: /api
version: v0.1.7
securitySchemes: 
    bearer-token: !include security.raml
securedBy: bearer-token

/auth:
    post:
        headers:
            Application-Key:
                type: string
                description: "The crypted AES key protecting the data"
            Application-Iv:
                type: string
                description: "The crypted AES iv protecting the data"
        body:
            application/json:
                type: object
                properties:
                    username: string
                    signature: string
        responses:
            200:
                headers:
                    Application-Key:
                        description: "The crypted AES key protecting the data"
                    Application-Iv:
                        description: "The crypted AES iv protecting the data"
                body:
                    text/plain:
                        description: "The crypted JWT token for the user session"
                        type: string
                        example: "sq5f4g65df565sq2d652fqsd2qs52d56qsd"
        securedBy: null
/factions:
    get:
        responses:
            200:
                body:
                    application/json:
                        type: object[]
                        items: !include factions/faction.raml
    /{id}:
        get:
            responses:
                200:
                    body:
                        application/json: !include factions/faction.raml
        /members:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include players/player.raml

        /planet-choices:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include planets/planet.raml

/map:
    get:
        responses:
            200:
                body:
                    application/json: !include maps/map.raml

/players:
    post:
        body:
            application/json:
                type: object
                properties:
                    faction_id: integer
                    planet_id: integer
        responses:
            204:
            403:
                description: "If the session account is already active"

    /me:
        get:
            responses:
                200:
                    body:
                        application/json: !include players/player.raml
    /{id}:
        get:
            responses:
                200:
                    body:
                        application/json: !include players/player.raml
        /planets:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include planets/planet.raml

/planets:
    /{id}:
        get:
            responses:
                200:
                    body:
                        application/json: !include planets/planet.raml
        /settings:
            put: #TODO
                body:
                    application/json: !include planets/settings.raml
        /building:
            post:
                body:
                    application/json: !include buildings/building-input.raml
                responses:
                    201:
                        body:
                            application/json: !include buildings/building-lowlink.raml
            /constructing:
                get: #TOD                        
        /fleets:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include fleets/fleet-lowlink.raml
        /ships:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include ships/ship-lowlink-planet.raml
            post: #TODO
                body:
                    application/json:
/servers:
    post:
        body:
            application/json:
                type: object
                properties:
                    name: string
                    type: string
                    signature: string
                example: |
                    {
                        "name": "Preprod",
                        "type": "multiplayer",
                        "signature": "ds56g9ht45ff5gf6g5ez6dagh5"
                    }
        responses:
            200:
                body:
                    application/json:
                        type: !include servers/server.raml
        securedBy: null
/systems:
    /{id}:
        get:
            responses:
                200:
                    body:
                        application/json: !include maps/system.raml
/me:
    /ship-models:
        get:
            responses:
                200:
                    body:
                        application/json:
                            type: object[]
                            items: !include ships/shipModel-nolink.raml
        post:
            body:
                application/json:
                    type: object
                    properties:
                            frame : string
                            name: string
                            slots:
                                type : object[]
                                items : !include ships/slot-nolink.raml
            responses:
                201:
                    body:
                        application/json: !include ships/shipModel-lowlink.raml
        /{id}:
            get:
                responses:
                    200:
                        body:
                            application/json: !include ships/shipModel-nolink.raml
/fleets:
    /{id}:
        get:
            description: Get fleet
            responses:
                200:
                    body:
                        application/json:
                            type: object[]
                            items: !include fleets/fleet-lowlink.raml
        /ships:
            get:
                description: Get ships in the fleet
                responses:
                    200:
                        body:
                            application/json:
                                type: object[]
                                items: !include ships/ship-lowlink.raml
            #/{id}:
            #    patch:
            #        responses:
            patch:
                description: move the ships with the given id into the fleet
                body:
                    application/json:
                        type: object
                        properties:
                            data-ships: integer[]
                responses:
                    202:
                        body:
                            application/json:
                                type: string
                                default : ""
                        
            delete:
                description: move the ships with the given id into the hangard
                body:
                    application/json:
                        type : object
                        properties:    

                            data-ships: integer[]
                responses:
                    204:
                        body:
                            application/json:
                                type: string
                                default : Deleted
        /journey:
            post:
                description : send fleet on journey sith steps given in input
                body:
                    application/json:
                        type: object[]
                        items:
                            type : object
                            properties:
                                planetId : integer
                                x:
                                    type: number
                                    format: float
                                y:
                                    type: number
                                    format: float
                responses:
                    202:
                        body:
                            application/json:
                                type : object[]
                                items: !include journeys/journeyStep-lowlink.raml
            patch:
                description : add step to journey
                body:
                    application/json:
                        type: object[]
                        items:
                            type : object
                            properties:
                                planetId : integer
                                x:
                                    type: number
                                    format: float
                                y:
                                    type: number
                                    format: float
                responses:
                    202:
                        body:
                            application/json:
                                type : object[]
                                items: !include journeys/journeyStep-lowlink.raml
            get:
                description: Get journey if exist
                responses:
                    200:
                        body:
                            application/json: !include journeys/journey-nolink.raml
        /steps:
            get:
                description: Get all steps remaining
                responses:
                    200:
                        body:
                            application/json: !include journeys/journeyStep-highlink.raml
            /{idStep}:
                delete:
                    description: Cancel step ad the folowing ones
                    responses:
                        204:
                            body:
                                application/json:
                                    type: string
                                    default : Deleted
                
        /range:
            get:
                description: Get maximum one jump distance
                responses:
                    200:
                        body:
                            application/json: !include fleets/range.raml
        /time:
            get:
                description: get time laws
                responses:
                    200:
                        body:
                            application/json: !include fleets/time.raml
    /range:
        get:
            description: "same as fleet/{id}/range : GET"
            responses:
                200:
                    body:
                        application/json: !include fleets/range.raml
    /time:
        get:
            description: "same as fleet/{id}/time : GET"
            responses:
                200:
                    body:
                        application/json: !include fleets/time.raml
    get:
        description: Get all fleets a player controlle
        responses:
            200:
                body:
                    application/json:
                        type: object[]
                        items: !include fleets/fleet.raml
    post:
        description: Crate a new fleet on selected planet id
        body:
            application/json:
                type: object
                properties:
                    "planet_id" : integer
        responses:
            201:
                body:
                    application/json: !include fleets/fleet-lowlink.raml
    delete:
        description: Delete fleet
        responses:
            204:
                body:
                    application/json:
                        type: string
                        default : Deleted
