#%RAML 1.0 DataType
type: object
displayName: Fleet
properties:
    id: integer
    player:
        type : object
        default : {}
    location:
        type : object
        default : {}
    journey:
        type : object
        default : {}
