#%RAML 1.0 DataType
type: object
displayName: Range
properties:
    same_system : !include time-dist.raml
    planet_to_planet: !include time-dist.raml
    planet_to_position: !include time-dist.raml
    position_to_position: !include time-dist.raml
    position_to_planet: !include time-dist.raml
