#%RAML 1.0 DataType
type: object
properties:
    id: integer
    #model:
        #type: object
        #default: {}
    position:
        type : integer
        minimum : 0
        maximum: 255
    module : string
