#%RAML 1.0 DataType
type: object
properties:
    id: integer
    name: string
    type: string
    planet:
        description: "Planet object"
        type: object
    status:
        type: string
        enum: ["constructing", "operational"]
    construction_state: !include construction_state.raml
    created_at: string
    updated_at: string
