#%RAML 1.0 DataType
type: object
properties:
    id: integer
    pseudo: string
    faction:
        description: "A faction object"
        type: object
        example: |
            {
                "id": 1,
                "name": "Les noirs vengeurs",
                "description": "Assoiffés de revanche, ces traqueurs ne lâchent jamais leur cible d'un pas"
            }
    is_active: boolean
    created_at: string
    updated_at: string
    wallet:
        type: integer
        minimum : 0
        maximum: 4294967295
